### ISSUE TITLE
Test Result

### ISSUE THREAD

**Issue by kimna4** [onlytailei/carla_cil_pytorch#3]
Thank you for sharing this project.

Can you achieve the same result with the paper (CARLA: An Open Urban Driving Simulator) using this project?

I can't take the released results.
Thank you

**Comment by onlytailei** [comment]
I haven't really set up the experiments for the Carla paper. On the other hand, the data augmentation methods are from their [ICRA2018 paper](https://arxiv.org/abs/1710.02410).
Actually, I used a different dataset separation for my work in [End-to-end driving deploying](https://arxiv.org/abs/1903.00821) and [VR-Goggles](https://tailei.ram-lab.com/static/papers/ral_2019_tai.pdf). The details can be found in the [supplement file](https://tailei.ram-lab.com/static/papers/ral_2019_tai_supplement.pdf).
